services:

  backend:
    build:
      context: ./backend
    container_name: interviewiq-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1


  frontend:
    build:
      context: ./frontend
    container_name: interviewiq-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules